<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.4 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Fri, 16 Jul 2010 23:50:13 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: shiala.chipsncheese.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'shiala.chipsncheese.com';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '0wnzj00';
$cfg['Servers'][$i]['only_db'] = array (
  0 => 'shiala_pfolio',
);

/* End of servers configuration */

$cfg['blowfish_secret'] = '4c4132afdad0b1.53316506';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['PersistentConnections'] = true;
$cfg['LeftDisplayLogo'] = false;
$cfg['ShowPhpInfo'] = true;
$cfg['Export'] = array (
  'compression' => 'zip',
);
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['SuhosinDisableWarning'] = 1;
$cfg['PmaNoRelation_DisableWarning'] = 1;
$cfg['Servers'][$i]['DisableIS'] = 1;

$cfg['Servers'][$i]['pmadb'] = 'shiala_pfolio';

?>
